### PR TITLE
Isolated router settings and router access/public IP separation

### PR DESCRIPTION
**Pull request by yo2loj**
- Router specific settings are in router.py
- Modified to accept different router access IP than public IP (useful for managing firewall settings)
- Added source address for IPIP interfaces, as it could conflict with other interfaces in the 44net
- Added the option to filter out explicit ("own") networks similar to bgp networks

### CODE REVIEW

**Comment by kd7lxl** [comment]
Hi Marius,

`/interface ipip remove [find name=%s]` and `/interface ipip remove %s` are identical on ROS, so this change is unnecessary.

With `router.py`, you make a number of usage changes, but have not updated the README to describe them. For example:
- Usage describes TARGET_IP command line argument, but you move this to `router.py`. Not only is this not explained, but it breaks functionality for users with multiple AMPR gateways--now they require multiple `router.py` files to target their multiple gateways.
- Username now defaults to "admin", meaning it does not inherit the username from the environment as it did before.
- Password now defaults to "password", meaning the SSH key in the user's environment will not be used. For users with SSH keys on their router, this breaks the script. (ROS does not support password login on accounts that have keys assigned.)

It looks like you have `own_networks` duplicate the behavior of `bgp_networks`. Maybe there is a better way. Instead of duplicating code, we could change the name to something more generic, like `ignore_networks`. This could be used to ignore routes in the encap regardless of reason--this could include ignoring your internal networks or external networks with direct routing agreements (such as the listed BGP networks).

What is the value of `pref-src`? We have dozens of addresses on our gateway and have not run into problems with it choosing the wrong source address. Can you give an example where `pref-src` is required?

I would prefer to review each of these changes as independent issues. However, as submitted, I am not interested in accepting any of them. If you could address the issues above, I will reconsider merging.

**Comment by yo2loj** [comment]
Hi Tom,

Of course, do not merge them becausee it is useless as you described.

There are 2 issues that need addressing in my opinion.
1. src address:
I have a loopback bridge that has 2 ampr addresses assigned, 44.182.21.254/24 for traffic addressed to the server and ax.25 radio links, and 44.182.20.254/24, for local networking and WiFi connections.
When using ping/traceroute from the router, I would prefer 44.182.21.254, while the router chooses the other one.
1. router address different from the gateway address:
   There are 3 use cases where this becomes relevant:
2. the gateway address is not assigned to the router, being e.g. dst-nated by another router in a DMZ
3. the GW address is dynamic and ROS has an issue there with hairpin routing
4. the user sets up a complex firewall by which it is more comfortably to access the router via its LAN ip (my case…).

So I actually hacked that script to fit my needs (and probably messed up the remove rule since there was an address remove instead of interface, which I thought was from your end - sorry about that).

Marius, YO2LOJ

**Comment by kd7lxl** [comment]
Okay, I see the value in those two changes now. I have never used the script in a NAT environment, so these issues did not occur to me. If you would like to resubmit them independently, with updated README, and without breaking existing functionality, I will accept them.

What I mean about not breaking existing functionality is that different router and gateway addresses should not be default. The script should assume they are the same, but offer the ability to override this.

**Comment by yo2loj** [comment]
Since I am not proficient in phyton, I am really guessing here…
But I will give them a try :-)

Marius

**Pull request closed without merging**
